name: Remove URLs from tv.txt  
  
on:  
  push:  
    paths:  
      - 'tv.txt'  # 只在这个文件发生变化时触发  
  workflow_dispatch:  # 允许手动触发  
  
jobs:  
  remove-urls:  
    runs-on: ubuntu-latest  
  
    steps:  
    - name: Checkout repository  
      uses: actions/checkout@v2  
  
    - name: Remove URLs from tv.txt  
      run: |  
        # 使用 sed 命令替换 'http://...' 或 'https://...' 为空字符串  
        sed -i 's|http[s?]://[^ ]*||g' tv.txt  
  
    - name: Commit changes  
      run: |  
        # 获取当前日期时间作为提交信息的一部分  
        commit_message="Updated tv.txt to remove URLs on $(date +'%Y-%m-%d %H:%M:%S')"  
        # 检查文件是否有更改（避免在没有更改时提交空提交）  
        if git diff --quiet --cached; then  
          echo "No changes to commit."  
        else  
          # 添加修改到暂存区  
          git add tv.txt  
          # 提交修改  
          git commit -m "$commit_message"  
          # 推送到远程仓库  
          git push  
        fi