name: Remove URLs from tv.txt  
  
on:  
  push:  
    branches:  
      - main  # 确保这是你的默认分支  
  pull_request:  
    branches:  
      - main  # 确保这是你的默认分支  
  
jobs:  
  remove-urls:  
    runs-on: ubuntu-latest  
  
    steps:  
    - name: Checkout repository  
      uses: actions/checkout@v3  # 使用最新版本的actions/checkout  
  
    - name: Ensure tv.txt exists and is not empty  
      run: |  
        #!/bin/bash  
        if [[ ! -f tv.txt || -s tv.txt == 0 ]]; then  
          echo "tv.txt does not exist or is empty."  
          exit 1  
        fi  
  
    - name: Remove lines containing http:// or https://  
      run: |  
        #!/bin/bash  
        grep -Ev '(http://|https://)' tv.txt > temp.txt && mv temp.txt tt.txt  
  
    - name: Commit and push changes if any  
      run: |  
        #!/bin/bash  
        if [[ -n "$(git status --porcelain | grep '^ M tt.txt$')" ]]; then  
          git config --local user.email "actions@126.com"  
          git config --local user.name "GitHub Action"  
          git add tt.txt  
          git commit -m "Remove lines containing http:// or https:// from tv.txt"  
          git push "${GITHUB_TOKEN}@github.com:${GITHUB_REPOSITORY}.git" HEAD:${GITHUB_REF}  
        fi  
      env:  
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}