name: Remove URLs from tv.txt  
  
on:  
  push:  
    branches:  
      - main  # 确保这是你的默认分支  
  pull_request:  
    branches:  
      - main  # 确保这是你的默认分支  
  
jobs:  
  remove-urls:  
    runs-on: ubuntu-latest  
  
    steps:  
    - name: Checkout repository  
      uses: actions/checkout@v3  # 使用最新版本的actions/checkout  
  
    - name: Remove lines containing http:// or https://  
      run: |  
        #!/bin/bash  
        # 使用grep -v命令去除包含http://或https://的行，并保存到tt.txt  
        grep -Ev '(http://|https://)' tv.txt > tt.txt  
  
    - name: Commit and push changes if any  
      run: |  
        #!/bin/bash  
        # 检查tt.txt是否有更改  
        if [[ -n "$(git diff --cached --name-only tt.txt)" ]]; then  
          # 配置git用户信息  
          git config --local user.email "actions@126.com"  
          git config --local user.name "GitHub Action"  
          # 添加更改到暂存区  
          git add tt.txt  
          # 提交更改  
          git commit -m "Remove lines containing http:// or https:// from tv.txt"  
          # 推送更改到远程仓库  
          git push  
        fi  
      env:  
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用GitHub提供的token进行推送